PREFIX operation:        <http://opencaesar.io/sierra/operation#>
PREFIX component:        <http://opencaesar.io/sierra/component#>
PREFIX function:        <http://opencaesar.io/sierra/function#>
PREFIX base:        <http://opencaesar.io/sierra/base#>
PREFIX oml:        <http://opencaesar.io/oml#>

SELECT DISTINCT	 *
WHERE {
	?capability a operation:Capability ;
		function:isImplementedBy [
			a function:Exchange ;
			(oml:hasSource|oml:hasTarget) [
				a function:Pin ;
				function:isPinOf ?function
			]
		]
}