PREFIX capability:        <http://opencaesar.io/sierra/capability#>
PREFIX component:        <http://opencaesar.io/sierra/component#>
PREFIX function:        <http://opencaesar.io/sierra/function#>
PREFIX base:        <http://opencaesar.io/sierra/base#>
PREFIX oml:        <http://opencaesar.io/oml#>

SELECT DISTINCT	 *
WHERE {
	?capability a capability:Capability ;
		function:isImplementedBy [
			a function:Chain ;
			base:aggregates [
				a function:Exchange ;
				oml:hasSource|oml:hasTarget [
					a function:Pin ;
					function:isPinOf ?function
				]
			]
		]
}